### ISSUE TITLE
wrong pySTEP link

### ISSUE THREAD

**Issue by dnerini** [ULHPC/puppet-sysadmins#3]
Hi there

I have noticed that in your parallel evolutionary computing page

https://ulhpc-tutorials.readthedocs.io/en/latest/python/advanced/scoop-deap/

you have wrongly linked the pySTEP library (presumably this one http://pystep.sourceforge.net/) to pySTEPS (https://github.com/pySTEPS/pysteps), which has nothing to do with evolutionary computing.

Kind regards
Daniele

**Comment by hcartiaux** [comment]
Hello,

I believe this has been fixed by Emmanuel in this commit:

commit 1dcfafaea765b61ac3f3b546e96e287f8522daed  [python/advanced/scoop-deap] : modification link to pySTEP lib

Thanks for reporting, please report your bug using hpc-tracker.uni.lu or in the corresponding github project https://github.com/ULHPC/tutorials

Best,

Hyacinthe
